require 'io/console'      
require 'pathname'
require 'highline/import'

require_relative 'bloodchalice/map'                                      
require_relative 'bloodchalice/movable'
require_relative 'bloodchalice/bloodchalice'
require_relative 'bloodchalice/game'
require_relative 'bloodchalice/player'
require_relative 'bloodchalice/zombie'